import AppKit
import CryptoKit

/// A fully materialized clipboard copy. No data providers or file contents are retained.
struct ClipboardPayload: Equatable {
    var items: [[String: Data]]
    static let maximumBytes = 16 * 1024 * 1024
    var fingerprint: Data {
        var hash = SHA256()
        func add(_ data: Data) {
            var length = UInt64(data.count).bigEndian
            withUnsafeBytes(of: &length) { hash.update(data: Data($0)) }
            hash.update(data: data)
        }
        for item in items {
            add(Data("item".utf8))
            for type in item.keys.sorted() { add(Data(type.utf8)); add(item[type]!) }
        }
        return Data(hash.finalize())
    }
    static func text(_ text: String) -> ClipboardPayload {
        ClipboardPayload(items: [[NSPasteboard.PasteboardType.string.rawValue: Data(text.utf8)]])
    }
}

enum ClipboardFailure: Error, LocalizedError {
    case changed, protectedContent, unsupported, tooLarge, writeFailed, expired, timedOut
    var errorDescription: String? {
        switch self {
        case .changed: return "Clipboard changed in another app. Check the clipboard before retrying."
        case .protectedContent: return "Clipboard content is marked private, temporary, or excluded from history. Nothing was copied or backed up."
        case .unsupported: return "This clipboard content cannot be safely backed up. Nothing was copied."
        case .tooLarge: return "Clipboard content exceeds the 16 MB backup limit. Nothing was copied."
        case .writeFailed: return "Clipboard write failed. The transcript is still available in the app."
        case .expired: return "That clipboard backup has expired or been cleared."
        case .timedOut: return "Reading the clipboard took too long. Nothing was copied."
        }
    }
}

protocol ClipboardAccess {
    var changeCount: Int { get }
    func read(expected: Int) throws -> ClipboardPayload
    func write(_ payload: ClipboardPayload, expected: Int, rollback: ClipboardPayload?) throws -> Int
}

extension ClipboardAccess {
    func write(_ payload: ClipboardPayload, expected: Int) throws -> Int {
        try write(payload, expected: expected, rollback: nil)
    }
}

final class SystemClipboard: ClipboardAccess {
    private let pasteboard: NSPasteboard
    init(_ pasteboard: NSPasteboard) { self.pasteboard = pasteboard }
    var changeCount: Int { pasteboard.changeCount }
    // Community privacy markers and older equivalents used by clipboard utilities.
    static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword", "com.typeit4me.clipping", "Pasteboard generator type"
    ]
    func read(expected: Int) throws -> ClipboardPayload {
        guard changeCount == expected else { throw ClipboardFailure.changed }
        let available = pasteboard.pasteboardItems
        guard available != nil || (pasteboard.types ?? []).isEmpty else { throw ClipboardFailure.unsupported }
        let source = available ?? []
        let declared = source.map { $0.types }
        guard source.count <= 128 else { throw ClipboardFailure.tooLarge }
        // Inspect every item's types before reading any potentially confidential bytes.
        for item in source {
            let types = item.types.map(\.rawValue)
            if !Self.excludedTypes.isDisjoint(with: types) { throw ClipboardFailure.protectedContent }
            if types.isEmpty || types.count > 128 || types.contains(where: {
                $0.localizedCaseInsensitiveContains("promise") || $0 == "NSFilesPromisePboardType"
            }) { throw ClipboardFailure.unsupported }
        }
        var bytes = 0
        var items = [[String: Data]]()
        for (item, types) in zip(source, declared) {
            var values = [String: Data]()
            for type in types {
                guard let data = item.data(forType: type) else { throw ClipboardFailure.unsupported }
                guard data.count <= ClipboardPayload.maximumBytes - bytes else { throw ClipboardFailure.tooLarge }
                bytes += data.count
                values[type.rawValue] = data
            }
            items.append(values)
        }
        guard changeCount == expected else { throw ClipboardFailure.changed }
        guard zip(source, declared).allSatisfy({ $0.0.types == $0.1 }) else { throw ClipboardFailure.changed }
        let payload = ClipboardPayload(items: items)
        _ = try objects(payload) // Refuse formats we cannot restore before copying over them.
        return payload
    }
    private func objects(_ payload: ClipboardPayload) throws -> [NSPasteboardItem] {
        try payload.items.map { values -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in values {
                guard item.setData(data, forType: NSPasteboard.PasteboardType(type)) else { throw ClipboardFailure.writeFailed }
            }
            return item
        }
    }
    func write(_ payload: ClipboardPayload, expected: Int, rollback: ClipboardPayload?) throws -> Int {
        // Prepare both the replacement and recovery data before touching the clipboard.
        let objects = try objects(payload)
        let recovery = try rollback.map { try self.objects($0) }
        guard changeCount == expected else { throw ClipboardFailure.changed }
        let cleared = pasteboard.clearContents()
        guard changeCount == cleared else { throw ClipboardFailure.changed }
        guard objects.isEmpty || pasteboard.writeObjects(objects) else {
            // Best-effort rollback only while no other app has taken ownership.
            if let recovery, changeCount == cleared {
                let recoveryCount = pasteboard.clearContents()
                if changeCount == recoveryCount && !recovery.isEmpty { _ = pasteboard.writeObjects(recovery) }
            }
            throw ClipboardFailure.writeFailed
        }
        // NSPasteboard has no atomic compare-and-swap. Check ownership as close to
        // the write as possible; never blindly retry against someone else's copy.
        guard changeCount == cleared else { throw ClipboardFailure.changed }
        return cleared
    }
}

struct ClipboardBackup {
    let id = UUID()
    let payload: ClipboardPayload
    let capturedAt: TimeInterval
    let isTranscript: Bool
}

/// Main-thread state. Reading external providers is delegated off the UI thread.
final class ClipboardManager {
    enum Slot { case lastCopy, beforeDictation }
    private struct Ownership {
        let count: Int
        let fingerprint: Data
        let isTranscript: Bool
        // Restoring a backup must never refresh that backup's lifetime.
        let originalCapture: TimeInterval?
    }
    private let clipboard: ClipboardAccess
    private let now: () -> TimeInterval
    private let reader = DispatchQueue(label: "com.zkdictate.clipboard.read")
    private var ownership: Ownership?
    private var reading = false
    private var operation = UUID()
    private var timeout: DispatchWorkItem?
    private var completion: ((Result<Void, Error>) -> Void)?
    private(set) var lastCopy: ClipboardBackup?
    private(set) var beforeDictation: ClipboardBackup?
    private(set) var enabled = false
    private(set) var lifetime: TimeInterval = 300
    private(set) var busy = false
    var onChange: (() -> Void)?

    init(clipboard: ClipboardAccess, now: @escaping () -> TimeInterval = { ProcessInfo.processInfo.systemUptime }) {
        self.clipboard = clipboard; self.now = now
    }
    func configure(enabled: Bool, minutes: Int) {
        self.enabled = enabled
        lifetime = TimeInterval([1, 5, 15].contains(minutes) ? minutes * 60 : 300)
        if !enabled { clear() } else { tick() }
        onChange?()
    }
    func remaining(_ backup: ClipboardBackup) -> Int { max(0, Int(ceil(lifetime - (now() - backup.capturedAt)))) }
    func backup(_ slot: Slot) -> ClipboardBackup? { slot == .lastCopy ? lastCopy : beforeDictation }
    func canRestore(_ slot: Slot) -> Bool {
        guard enabled, !busy, let backup = backup(slot), now() - backup.capturedAt < lifetime,
              let ownership, clipboard.changeCount == ownership.count else { return false }
        return true
    }
    func tick() {
        if let lastCopy, now() - lastCopy.capturedAt >= lifetime { self.lastCopy = nil }
        if let beforeDictation, now() - beforeDictation.capturedAt >= lifetime { self.beforeDictation = nil }
        if let ownership, clipboard.changeCount != ownership.count { self.ownership = nil }
        onChange?()
    }
    func cancelPending() {
        operation = UUID(); timeout?.cancel(); timeout = nil
        let pending = completion; completion = nil; busy = false
        onChange?()
        pending?(.failure(ClipboardFailure.expired))
    }
    func clear() {
        lastCopy = nil; beforeDictation = nil
        cancelPending()
    }
    private func finish(_ result: Result<Void, Error>) {
        timeout?.cancel(); timeout = nil; busy = false
        let callback = completion; completion = nil
        onChange?(); callback?(result)
    }
    private func readCurrent(_ action: @escaping (ClipboardPayload, Int) throws -> Void,
                             completion: @escaping (Result<Void, Error>) -> Void) {
        guard !busy, !reading else { completion(.failure(ClipboardFailure.changed)); return }
        tick()
        let count = clipboard.changeCount
        let token = UUID(); operation = token; busy = true; reading = true; self.completion = completion
        onChange?()
        let timeout = DispatchWorkItem { [weak self] in
            guard let self, self.operation == token, self.busy else { return }
            self.operation = UUID(); self.finish(.failure(ClipboardFailure.timedOut))
        }
        self.timeout = timeout
        DispatchQueue.main.asyncAfter(deadline: .now() + 3, execute: timeout)
        reader.async { [weak self, clipboard] in
            let result = Result { try clipboard.read(expected: count) }
            DispatchQueue.main.async { [weak self] in
                guard let self else { return }
                self.reading = false
                guard self.operation == token, self.busy else { return }
                do {
                    let payload = try result.get()
                    guard self.clipboard.changeCount == count else { throw ClipboardFailure.changed }
                    try action(payload, count)
                    self.finish(.success(()))
                } catch {
                    if case ClipboardFailure.changed = error { self.ownership = nil }
                    if case ClipboardFailure.protectedContent = error { self.lastCopy = nil; self.beforeDictation = nil }
                    self.finish(.failure(error))
                }
            }
        }
    }
    func copy(_ text: String, completion: @escaping (Result<Void, Error>) -> Void) {
        let next = ClipboardPayload.text(text)
        guard !busy else { completion(.failure(ClipboardFailure.changed)); return }
        if !enabled {
            do {
                let count = try clipboard.write(next, expected: clipboard.changeCount)
                ownership = Ownership(count: count, fingerprint: next.fingerprint, isTranscript: true, originalCapture: nil)
                completion(.success(()))
            }
            catch { completion(.failure(error)) }
            return
        }
        readCurrent({ [weak self] previous, count in
            guard let self else { return }
            let currentOwner = self.ownership.flatMap { $0.count == count && $0.fingerprint == previous.fingerprint ? $0 : nil }
            // Manual repeated copies do not replace backups or extend expiry.
            if currentOwner?.isTranscript == true && previous == next { return }
            let capturedAt = currentOwner?.originalCapture ?? self.now()
            let saved = ClipboardBackup(payload: previous, capturedAt: capturedAt, isTranscript: currentOwner?.isTranscript ?? false)
            let newCount = try self.clipboard.write(next, expected: count, rollback: previous)
            self.lastCopy = self.now() - capturedAt < self.lifetime ? saved : nil
            if !saved.isTranscript { self.beforeDictation = self.lastCopy }
            self.ownership = Ownership(count: newCount, fingerprint: next.fingerprint, isTranscript: true, originalCapture: nil)
            self.tick()
        }, completion: completion)
    }
    func restore(_ slot: Slot, completion: @escaping (Result<Void, Error>) -> Void) {
        tick()
        guard canRestore(slot), let id = backup(slot)?.id else { completion(.failure(ClipboardFailure.expired)); return }
        readCurrent({ [weak self] current, count in
            guard let self, let backup = self.backup(slot), backup.id == id,
                  self.now() - backup.capturedAt < self.lifetime else { throw ClipboardFailure.expired }
            guard let owner = self.ownership, owner.count == count, owner.fingerprint == current.fingerprint else { throw ClipboardFailure.changed }
            let newCount = try self.clipboard.write(backup.payload, expected: count, rollback: current)
            self.ownership = Ownership(count: newCount, fingerprint: backup.payload.fingerprint,
                                       isTranscript: backup.isTranscript, originalCapture: backup.capturedAt)
            // Keep both choices, allowing the user to switch between them.
        }, completion: completion)
    }
}
